import NavBar from "@/components/NavBar";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { TransitionEffect } from "@/components/TransitionEffect";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans bg-light`}>
        <NavBar />
        <main className="min-h-[87.5vh] w-full flex flex-col">{children}</main>
      </body>
    </html>
  );
}
